name: encounter
description: Cross-platform contact tracing on the web

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  intl: ^0.16.1
  searchable_dropdown: ^1.1.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/01.png
    - assets/images/02.png
    - assets/images/03.png
    - assets/images/04.png
    - assets/images/05.png
    - assets/images/06.png
